#!/usr/bin/env bash
set -euo pipefail

# --- получаем актуальную стабильную версию Maven 3 ---
MAVEN_VERSION=$(curl -sSL https://maven.apache.org/download.html \
  | grep -oP 'apache-maven-\K[0-9.]+' | head -1)
BASE_URL="https://dlcdn.apache.org/maven/maven-3/${MAVEN_VERSION}/binaries"

# --- проверка прав ---
if (( EUID != 0 )); then
  echo "❌ Запустите скрипт через sudo" >&2
  exit 1
fi

# --- установка Maven ---
install_dir="/opt/apache-maven-${MAVEN_VERSION}"
mkdir -p "$install_dir"
curl -sSfL "${BASE_URL}/apache-maven-${MAVEN_VERSION}-bin.tar.gz" \
  | tar -xzf - --strip-components=1 -C "$install_dir"
ln -sf "${install_dir}/bin/mvn" /usr/local/bin/mvn

# --- переменные прокси (с дефолтами) ---
PROXY_HOST="${PROXY_HOST:-proxy}"
PROXY_PORT="${PROXY_PORT:-8080}"
PROXY_SCHEME="${PROXY_SCHEME:-http}"
PROXY_ID="${PROXY_ID:-corp-proxy}"
NON_PROXY_HOSTS="${NON_PROXY_HOSTS:-localhost|*.local|127.0.0.1|::1}"

# --- убеждаемся, что mvn в PATH ---
command -v mvn >/dev/null || {
  echo "❌ Maven не найден; проверьте установку" >&2
  exit 1
}

# --- создаём settings.xml ---
SETTINGS_DIR="$HOME/.m2"
mkdir -p "$SETTINGS_DIR"
SETTINGS_FILE="$SETTINGS_DIR/settings.xml"

cat >"$SETTINGS_FILE" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!-- GENERATED by setup-maven.sh -->
<settings xmlns="http://maven.apache.org/SETTINGS/1.4.0">
  <proxies>
    <proxy>
      <id>${PROXY_ID}</id>
      <active>true</active>
      <protocol>${PROXY_SCHEME}</protocol>
      <host>${PROXY_HOST}</host>
      <port>${PROXY_PORT}</port>
      <nonProxyHosts>${NON_PROXY_HOSTS}</nonProxyHosts>
    </proxy>
  </proxies>
</settings>
EOF

chmod 644 "$SETTINGS_FILE"

echo "✅ settings.xml создан: $SETTINGS_FILE"
